batch/urls.py
from django.urls import path
from batch.views import create_batch, update_batch, detail_batch, list_batch, delete_batch

app_name = 'batch'

urlpatterns = [
    path('create_batch',create_batch.createBatch, name = 'create_batch'),
    path('update_batch/<str:id>',update_batch.updateBatch, name = 'update_batch'),
    path('detail_batch/<str:id>',detail_batch.detailBatch, name = 'detail_batch'),
    path('list_batch',list_batch.listBatch, name = 'list_batch'),
    path('delete_batch/<str:id>',delete_batch.deleteBatch,name = 'delete_batch')



    
]

registration_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    path('batch/',include('batch.urls')),
    path('',include('education.urls')),
    path('',include('family.urls')),
    path('',include('college.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batch/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist


# Create your models here.
class Batch(models.Model):
    batch_name = models.CharField(max_length=50)


    class Meta:
        verbose_name = 'Batch_name'
        verbose_name_plural = "Batch_names"


    @staticmethod
    def get_batch_by_id(id):
        try:
            return Batch.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

    @staticmethod
    def get_all_batch():
        return Batch.objects.all()

    def __str__(self):
        return self.batch_name

class Semester(models.Model):
    semester_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default = True)

    class Meta:
        verbose_name = 'Semester_name'
        verbose_name_plural = "Semester_names"

    
    @staticmethod
    def get_all_semester():
        return Semester.objects.all()

    @staticmethod
    def get_semester_by_id(id):
        try:
            return Semester.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

    def __str__(self):
        return self.semester_name

class Faculty(models.Model):
    faculty_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Faculty_name'
        verbose_name_plural = "Faculty_names"

    @staticmethod
    def get_all_fauclty():
        return Faculty.objects.all()

    @staticmethod
    def get_faculty_by_id(id):
        try:
            return Faculty.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

    def __str__(self):
        return self.faculty_name   

batch/forms.py
from batch.models import Batch
from django import forms

class BatchForm(forms.ModelForm):
    class Meta:
        model = Batch
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','id':'exampleInputBatchName'})
        }

batch/views/create_batch.py
from django.shortcuts import render,redirect
from batch.forms import BatchForm

def createBatch(request):
    if request.method == "GET":
        form = BatchForm()
        return render(request,'batch/batchCreate.html',{'form':form})
    elif request.method == "POST":
        form = BatchForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('batch:list_batch')
        return render(request,'batch/batchCreate.html',{'form':form})

batch/views/delete_batch.py
from django.http import Http404
from django.shortcuts import redirect
from batch.models import Batch
from django.shortcuts import redirect, render
from django.http import Http404


def deleteBatch(request,id):
    batch = Batch.get_batch_by_id(id)
    if batch:
        if request.method == "POST":
            batch.delete()
            return redirect('batch:list_batch')
        return render(request,'batch/batchDelete.html')
    else:
        raise Http404()

batch/views/detail_batch.py
from django.http import Http404
from django.shortcuts import render
from batch.models import Batch
from django.http import Http404

def detailBatch(request,id):
    context = {}
    batch = Batch.get_batch_by_id(id)
    if batch:
        context['batch'] = batch
        return render(request, 'batch/batchDetail.html',context)
    else:
        raise Http404()

batch/views/list_batch.py
from batch.models import Batch
from django.shortcuts import render


def listBatch(request):
    context = {}
    batches = Batch.get_all_batch()
    context ={'batches':batches} 
    return render(request, 'batch/batchList.html', context)

batch/views/update_batch.py
from batch.models import Batch
from batch.forms import BatchForm
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import Http404, HttpResponseRedirect


def updateBatch(request, id):
    context = {}
    batch = Batch.get_batch_by_id(id)
    if batch:
        if request.method == "POST":
            form = BatchForm(request.POST, instance = batch)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('batch:detail_batch', args = [batch.id]))
        else:
            form = BatchForm(instance=batch)
            context = {'batch':batch, 'form':form}
        return render(request,'batchCreate.html',context)
    else:
        raise Http404()

batch/templates/batch/batchCreate.html
{% extends 'student/base.html' %}

{% block content %}


<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Batch Registration</h3>
                    </div>
                    <div>
                        <br><br><br>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method = "POST">{% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<section>
                
 



{% endblock content %}

batch/templates/batch/batchDelete.html
{% extends 'student/base.html' %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
            <!-- general form elements -->
                <div class="card card-primary">
                    <form method = "POST">
                        {% csrf_token %}
                        Are you sure to delete this student?
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

batch/templates/batch/batchDetail.html
{% extends 'student/base.html' %}

{% block content %}

<div class = "wrapper">

    <h4 class="mb-2 mt-4">Batch Detail</h4>
        <h5 class="mb-2">{{batch.batch_name}}</h5>
        <div class="row">
          <div class="col-md-3">
            <div class="card card-primary collapsed-card">
              <div class="card-header">
                <h3 class="card-title">{{batch.batch_name}} Details</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <span>Batch:<p>{{batch.batch_name}}<p></span><br>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
</div>

{% endblock content %}

batch/templates/batch/batchList.html
{% extends 'student/base.html' %}

{% block content %}

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Student List</h3>

          <div class="card-tools">
            {% comment %} <div class="input-group input-group-sm" style="width: 150px;"> {% endcomment %}
                <a href = "{% url 'batch:create_batch' %}" class = "btn btn-primary btn-sm">Add Batch</a>
              {% comment %} <button type = "btn" class = "btn btn-default"><a href = "{}">Add Student</a><button> {% endcomment %}
              {% comment %} </div> {% endcomment %}
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>SN</th>
                <th>Batch Name</th>


              </tr>
            </thead>
            {% for batch in batches %}
            <tbody>
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{batch.batch_name}}</td>
                <td>
                    <a href = "{% url 'batch:detail_batch' batch.id %}" class = "btn btn-info btn-sm"><span class = "fa fa-eye"></span></a>
                    <a href = "{% url 'batch:update_batch' batch.id %}" class = "btn btn-warning btn-sm"><span class = "fa fa-edit"></span></a>
                    <a href = "{% url 'batch:delete_batch' batch.id %}" class = "btn btn-danger btn-sm"><span class = "fa fa-trash"></span></a>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


{% endblock content %}

batch/templates/batch/batchUpdate.html
{% extends 'student/base.html' %}

{% block content %}


<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Batch Registration</h3>
                    </div>
                    <div>
                        <br><br><br>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action = "" method = "POST">{% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<section>
                
 



{% endblock content %}