batch/urls.py
from django.urls import path
from batch.views import create_batch, update_batch, detail_batch, list_batch, delete_batch

app_name = 'batch'

urlpatterns = [
    path('create_batch',create_batch.createBatch, name = 'create_batch'),
    path('update_batch/<str:id>',update_batch.updateBatch, name = 'update_batch'),
    path('detail_batch/<str:id>',detail_batch.detailBatch, name = 'detail_batch'),
    path('list_batch',list_batch.listBatch, name = 'list_batch'),
    path('delete_batch/<str:id>',delete_batch.deleteBatch,name = 'delete_batch')



    
]

college/urls.py
from django.urls import path
from .views import collegeinfo_create,collegeinfo_list,collegeinfo_update,collegeinfo_detail, collegeinfo_delete

app_name = 'college_info'

urlpatterns = [
    # requires student id
    path('collegeinfo_create/<str:id>',collegeinfo_create.createCollegeInfo,name = 'collegeinfo_create'),
    # requires collegeinfo id
    path('collegeinfo_list',collegeinfo_list.listCollegeInfo, name = 'collegeinfo_list'),
    path('collegeinfo_update/<str:id>',collegeinfo_update.updateCollegeInfo, name = 'collegeinfo_update'),
    path('collegeinfo_detail/<str:id>',collegeinfo_detail.collegeInfoDetail,name = 'collegeinfo_detail'),
    path('collegeinfo_delete/<str:id>',collegeinfo_delete.deleteCollegeInfo,name = 'collegeinfo_delete')

]

education/urls.py
from django.urls import path
from .views import educationinfo_create,eudcationinfo_list,educationinfo_detail,educationinfo_update,educationinfo_delete

app_name = 'education'

urlpatterns = [
    
   # requires student id
    path('educationinfo_create/<str:id>',educationinfo_create.createEducationInfo,name = 'educationinfo_create'),
    path('educationinfo_list',eudcationinfo_list.listEducationInfo,name = 'educationinfo_list'),
    # requires educationinformation id
    path('educationinfo_detail/<str:id>',educationinfo_detail.educationinfoDetail,name = 'educationinfo_detail'),
    # requires educationinformation id
    path('educationinfo_update/<str:id>',educationinfo_update.updateEducationInfo,name = 'educationinfo_update'),
   # requires educationinformation id
    path('educationinfo_delete/<str:id>',educationinfo_delete.deleteEducationInfo,name = 'educationinfo_delete'),

]

registration_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    path('batch/',include('batch.urls')),
    path('',include('education.urls')),
    path('',include('family.urls')),
    path('',include('college.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from operator import imod
from django.urls import path

from student.views import create_student, homeview,update_student,student_detail,student_list,homeview,delete_student
app_name = 'student'

urlpatterns = [
    path('',homeview.Home, name = 'home'),
    path('create_student',create_student.create_student, name = 'create_student'),
    path('update_student/<str:id>',update_student.updateStudent, name = 'update_student'),
    path('detail_student/<str:id>',student_detail.studentDetail, name = 'detail_student'),
    path('student_list',student_list.studentList, name = 'student_list'),
    path('delete_student/<str:id>',delete_student.deleteStudent,name = 'delete_student'),



 
]

student/models.py
from tabnanny import verbose
from tarfile import REGTYPE
from django.db import models
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    mobile = models.CharField(max_length = 10, unique=True, db_index=True)
    citizenship = models.CharField(max_length=20, unique=True, db_index=True)
    gender = models.CharField(max_length = 10)
    blood_group = models.CharField(max_length=5)
    temp_address = models.CharField(max_length=150, null= True, blank = True)
    perm_address = models.CharField(max_length=150)
    dob = models.CharField(max_length=150)
    is_active = models.BooleanField(default = True)
    is_alumi = models.BooleanField(default=False)
    picture = models.ImageField(upload_to = 'student_picture', default = 'scooter.png', null = True, blank = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'student'
        verbose_name_plural = "students"

    def __str__(self):
        return self.name

    @staticmethod
    def get_all_student():
        return Student.objects.all()

    @staticmethod
    def get_student_by_id(id):
        try:
            return Student.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

student/forms.py
from dataclasses import field
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','id':'exampleInputName'}),
            'email': forms.TextInput(attrs={'class':'form-control','id':'exampleInputEmail'}),
            'mobile': forms.TextInput(attrs={'class':'form-control','id':'exampleInputMobile'}),
            'citizenship': forms.TextInput(attrs={'class':'form-control','id':'exampleInputMobile'}),
            'gender': forms.TextInput(attrs={'class':'form-control','id':'exampleInputGender'}),
            'blood_group': forms.TextInput(attrs={'class':'form-control','id':'exampleInputBloodGroup'}),
            'temp_address': forms.TextInput(attrs={'class':'form-control','id':'exampleInputTempAddress'}),
            'perm_address': forms.TextInput(attrs={'class':'form-control','id':'exampleInputPermanentAddress'}),
            'dob':forms.TextInput(attrs = {'class':'form-control','id':'exampleInputDob'}),
            'is_active': forms.CheckboxInput(attrs = {'class':'form-control', 'id':'exampleInputIsactive'}),
            'is_alumi': forms.CheckboxInput(attrs = {'class':'form-control', 'id':'exampleInputIsalumi'}),
            'picture': forms.FileInput(attrs = {'class':'form-control', 'id':'exampleInputFile'}),

        }


        # widgets = {
        #     # 'student': forms.HiddenInput(attrs={'class':'form-control','id':'exampleInputStudent', 'value' : {{student}}}),
        #     'symbol': forms.TextInput(attrs={'class':'form-control','id':'exampleInputSymbol'}),
        #     'board': forms.TextInput(attrs={'class':'form-control','id':'exampleInputBoard'}),
        #     'institution_name': forms.TextInput(attrs={'class':'form-control','id':'exampleInputInstitution'}),
        #     'cgpa': forms.TextInput(attrs={'class':'form-control','id':'exampleInputCgpa'}),
        #     'passed_year': forms.TextInput(attrs={'class':'form-control','id':'exampleInputPassedYear'})
        # }
    

student/views/create_student.py
from django.shortcuts import render, redirect
from django.contrib import messages
from student.models import *

from student.forms import StudentForm

def create_student(request):
    if request.method == "GET":
        form = StudentForm()
        return render(request,'student/student_form.html',{'form':form})
    elif request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            form.save()
            messages.success(request,f"Account for {name} successfully created.")
            return redirect('family:family_list')
        return render(request,'student/student_form.html',{'form':form})

student/views/delete_student.py
from django.http import HttpResponse
from django.shortcuts import redirect
from student.models import Student
from django.shortcuts import redirect, render
from django.http import Http404

def deleteStudent(request,id):
    context = {}
    student = Student.get_student_by_id(id)
    if student:
        if request.method == "POST":
            student.delete()
            return redirect('student:student_list')
        return render(request,'student/student_delete.html')
    else:
        raise Http404()

student/views/homeview.py
from student.models import Student
from django.shortcuts import render


def Home(request):
    context = {}
    student_list = Student.get_all_student()
    context ={'students':student_list} 
    return render(request, 'student/student_list.html', context)

student/views/student_detail.py
from django.http import Http404
from django.shortcuts import render
from student.models import Student
from django.http import Http404

def studentDetail(request,id):
    context = {}
    student = Student.get_student_by_id(id)
    if student:
        context['student'] = student
        return render(request, 'student/student_detail.html',context)
    else:
        raise Http404()

student/views/student_list.py
from student.models import Student
from django.shortcuts import render


def studentList(request):
    context = {}
    student_list = Student.get_all_student()
    # eduinfo = student_list.educationinformation_set.all()
    context ={'students':student_list} 
    return render(request, 'student/student_list.html', context)

student/views/update_student.py
from student.models import Student
from django.contrib import messages
from student.forms import StudentForm
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404

def updateStudent(request, id):
    context = {}
    student = Student.get_student_by_id(id)
    if student:
        if request.method == "POST":
            form = StudentForm(request.POST, instance = student)
            if form.is_valid():
                form.save()
                messages.success(request,"Updated Successfully")
                return HttpResponseRedirect(reverse('student:detail_student', args = [student.id]))
        else:
            form = StudentForm(instance=student)
            context = {'form':form}
        return render(request,'student/student_form.html',context)
    else:
        raise Http404()

student/templates/student/student_delete.html
{% extends 'student/base.html' %}

{% block title %}Delete Student{% endblock %}


{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
            <!-- general form elements -->
                <div class="card card-primary">
                    <form method = "POST">
                        {% csrf_token %}
                        Are you sure to delete this student?
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

student/templates/student/student_detail.html
{% extends 'student/base.html' %}

{% block title %}Student Detail{% endblock %}


{% block content %}

<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class = "wrapper">

    <h4 class="mb-2 mt-4">{{student.name}}||Detail</h4>
        <h5 class="mb-2">{{student.name}}</h5>
        <div class="row">
          <div class="col-md-3">
            <div class="card card-primary collapsed-card">
              <div class="card-header">
                <h3 class="card-title">{{student.name}} Details</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <span>Email:<p>{{student.email}}<p></span><br>
                <span>Mobile:<p>{{student.mobile}}<p></span><br>
                <span>CitizenShip:<p>{{student.citizenship}}<p></span><br>
                <span>Gender:<p>{{student.gender}}<p></span><br>
                <span>Blood Group:<p>{{student.blood_group}}<p></span><br>
                <span>Temporary Address:<p>{{student.temp_address}}<p></span><br>
                <span>Permanent Address:<p>{{student.perm_address}}<p></span><br>
                <span>Date of Birth:<p>{{student.dob}}<p></span><br>
                <span>Is Alumi:<p>{{student.is_alumi}}<p></span><br>
                <span>Picture:<p>{{student.picture.url}}<p></span><br>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
</div>

{% endblock content %}

student/templates/student/student_form.html
{% extends 'student/base.html' %}


{% block title %}Create Student{% endblock %}

{% block content %}


{% if messages %}
  {% for message in messages %}
      {{message}}
  {% endfor %}
{% endif %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                    <h3 class="card-title">Student Registration</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method = "POST">{% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                        
                        {% comment %} <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputName">Name</label>
                                <input type="text" class="form-control" id="exampleInputName"  name = 'name' placeholder="Enter Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" name = 'email' placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputMobile">Mobile Number</label>
                                <input type="text" class="form-control" id="exampleInputMobile" name = 'mobile' placeholder="Enter Mobile">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputCitizenship">CitizenShip Id</label>
                                <input type="text" class="form-control" id="exampleInputCitizenship" name = 'citizenship' placeholder="Enter Citizenship Id">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputGender">Gender</label>
                                <input type="text" class="form-control" id="exampleInputGender" name = 'gender' placeholder="Enter Gender" value = "male">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputBloodGroup">Blood Group</label>
                                <input type="text" class="form-control" id="exampleInputBloodGroup" name = 'blood_group'placeholder="Enter Blood Group">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputTempAddress">Temporary address</label>
                                <input type="text" class="form-control" id="exampleInputTempAddress" name = 'temporary_address'placeholder="Temporary Address">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputTempAddress">Permanent address</label>
                                <input type="text" class="form-control" id="exampleInputPermanentAddress" name = 'permanent_address'placeholder="Permanent Address">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputDob">Date of Birth</label>
                                <input type="text" class="form-control" id="exampleInputDob" name = 'dob' placeholder="Date of Birth">
                            </div> {% endcomment %}
                            {% comment %} <div class="form-group"> {% endcomment %}
                                {% comment %} <label for="exampleInputTempAddress">Is active</label>
                                <input type="checkbox" class="form-control" id="exampleInputIsactive" name = 'is_active'>
                            </div>
                            <div class="form-group"> {% endcomment %}
                                {% comment %} <label for="exampleInputIsalumi">Is Alumi</label>
                                <input type="checkbox" class="form-control" id="exampleInputIsalumi" name = 'is_alumi'>
                            </div>
                            <div class="form-group"> {% endcomment %}
                                {% comment %} <label for="exampleInputFile">Picture</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile" name = "picture">Choose picture</label>
                                    </div>
                                </div> {% endcomment %}
                            {% comment %} </div> {% endcomment %}
                            {% comment %} <div class="card-footer">
                                <input type="submit" class="btn btn-primary" value = "Submit">
                            </div>
                        </div> {% endcomment %}
                    {% comment %} </form> {% endcomment %}
                </div>

                <!-- /.card-body -->

                {% comment %} <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form> {% endcomment %}
          </div>
          <!-- /.card -->
            </div>
        </div>
    </div>
</section>


{% endblock content %}

student/templates/student/student_list.html
{% extends 'student/base.html' %}

{% block title %}List Student{% endblock %}


{% block content %}
{% load check%}
{% load custom_filter %}


<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Student List</h3>

          <div class="card-tools">
            {% comment %} <div class="input-group input-group-sm" style="width: 150px;"> {% endcomment %}
                <a href = "{% url 'student:create_student' %}" class = "btn btn-primary btn-sm">Add Student</a>
              {% comment %} <button type = "btn" class = "btn btn-default"><a href = "{}">Add Student</a><button> {% endcomment %}
              {% comment %} </div> {% endcomment %}
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>SN</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Action</th>
                <th>-------</th>
                <th>-------</th>
                <th>-------</th>
              </tr>
            </thead>
            {% for student in students %}
            <tbody>
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{student.name}}</td>
                <td>{{student.email}}</td>
                <td>{{student.mobile}}</td>
                <td>
                    <a href = "{% url 'student:detail_student' student.id %}" class = "btn btn-info btn-sm"><span class = "fa fa-eye"></span></a>
                    <a href = "{% url 'student:update_student' student.id %}" class = "btn btn-warning btn-sm"><span class = "fa fa-edit"></span></a>
                    <a href = "{% url 'student:delete_student' student.id %}" class = "btn btn-danger btn-sm"><span class = "fa fa-trash"></span></a>
                </td>
                {% if student|check_eduinfo %}
                <td>
                  <a href = "educationinfo_detail/{{student|view_edu}}" class = "btn btn-block btn-light"><span class = "fa fa-eye">&nbsp</span>EduInfo</a>
                </td>
                {% else %}
                  <td>
                    <a href = "{% url 'education:educationinfo_create' student.id %}" class = "btn btn-block btn-dark"><span class = "fa fa-plus">&nbsp</span>EduInfo</a>
                  </td>
                {% endif %}
                {% if student|check_familyinfo %}
                  <td>
                    <a href = "familyinfo_detail/{{student|view_familyinfo}}" class = "btn btn-block btn-light"><span class = "fa fa-eye">&nbsp</span>FamilyInfo</a>
                  </td>
                {% else %}
                  <td>
                    <a href = "{% url 'college_info:collegeinfo_create' student.id %}" class = "btn btn-block btn-dark"><span class = "fa fa-plus">&nbsp</span>FamilyInfo</a>
                  </td>
                {% endif %}
                {% if student|check_collegeinfo %}
                <td>
                  <a href = "collegeinfo_detail/{{student|view_collegeinfo}}" class = "btn btn-block btn-light"><span class = "fa fa-eye">&nbsp</span>CollegeInfo</a>
                </td>
                {% else %}
                  <td>
                    <a href = "{% url 'education:educationinfo_create' student.id %}" class = "btn btn-block btn-dark"><span class = "fa fa-plus">&nbsp</span>CollegeInfo</a>
                  </td>
                {% endif %}
                
              
                </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


{% endblock content %}