batch/urls.py
from django.urls import path
from batch.views import create_batch, update_batch, detail_batch, list_batch, delete_batch

app_name = 'batch'

urlpatterns = [
    path('create_batch',create_batch.createBatch, name = 'create_batch'),
    path('update_batch/<str:id>',update_batch.updateBatch, name = 'update_batch'),
    path('detail_batch/<str:id>',detail_batch.detailBatch, name = 'detail_batch'),
    path('list_batch',list_batch.listBatch, name = 'list_batch'),
    path('delete_batch/<str:id>',delete_batch.deleteBatch,name = 'delete_batch')



    
]

college/urls.py
from django.urls import path
from .views import collegeinfo_create,collegeinfo_list,collegeinfo_update,collegeinfo_detail, collegeinfo_delete

app_name = 'college_info'

urlpatterns = [
    # requires student id
    path('collegeinfo_create/<str:id>',collegeinfo_create.createCollegeInfo,name = 'collegeinfo_create'),
    # requires collegeinfo id
    path('collegeinfo_list',collegeinfo_list.listCollegeInfo, name = 'collegeinfo_list'),
    path('collegeinfo_update/<str:id>',collegeinfo_update.updateCollegeInfo, name = 'collegeinfo_update'),
    path('collegeinfo_detail/<str:id>',collegeinfo_detail.collegeInfoDetail,name = 'collegeinfo_detail'),
    path('collegeinfo_delete/<str:id>',collegeinfo_delete.deleteCollegeInfo,name = 'collegeinfo_delete')

]

registration_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    path('batch/',include('batch.urls')),
    path('',include('education.urls')),
    path('',include('family.urls')),
    path('',include('college.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college/models.py
from django.db import models
from student.models import Student
from batch.models import Batch, Semester, Faculty
from django.core.exceptions import ObjectDoesNotExist


# Create your models here.

class CollegeInformation(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    batch = models.ForeignKey(Batch, on_delete=models.DO_NOTHING)
    semester = models.ForeignKey(Semester, on_delete=models.DO_NOTHING)
    faculty= models.ForeignKey(Faculty, on_delete = models.DO_NOTHING)
    tu_registration_number = models.CharField(max_length=100)
    symbol_number = models.CharField(max_length=50)

    class Meta:
        ordering = ('symbol_number',)
        verbose_name = "CollegeInformation"
        verbose_name_plural = "CollegeInformations"

    @staticmethod
    def get_all_collegeinfo():
        return CollegeInformation.objects.all()

    @staticmethod
    def get_collegeinfo_by_id(id):
        try:
            return CollegeInformation.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

college/forms.py
from college.models import CollegeInformation
from django import forms

class CollegeInfoForm(forms.ModelForm):
    class Meta:
        model = CollegeInformation
        fields = "__all__"

college/views/collegeinfo_create.py
from http.client import HTTPResponse
from college.models import CollegeInformation
from student.models import Student
from batch.models import Batch,Semester,Faculty
from college.forms import CollegeInfoForm
from django.shortcuts import render,redirect
from django.http import Http404

def createCollegeInfo(request,id):
    context = {}
    student = Student.get_student_by_id(id)
    if student:
        batches = Batch.get_all_batch()
        semesters = Semester.get_all_semester()
        faculties = Faculty.get_all_fauclty()


        if request.method == "POST":
            batchId = request.POST.get('batch')
            semesterId = request.POST.get('semester')
            facultyId =request.POST.get('faculty')
            tu_registration = request.POST.get('tu_registration_number'),
            symbol_number = request.POST.get('symbol_number')

            batch = Batch.get_batch_by_id(int(batchId))
            semester = Semester.get_semester_by_id(int(semesterId))
            faculty = Faculty.get_faculty_by_id(int(facultyId))
            collegeinfo = CollegeInformation(
                student = student,
                batch = batch,
                semester = semester,
                faculty = faculty,
                tu_registration_number = tu_registration,
                symbol_number = symbol_number
            )
            collegeinfo.save()
            return redirect('college_info:collegeinfo_list')
        else:
            context = {
                'student':student,
                'batches':batches,
                'semesters':semesters,
                'faculties':faculties
            }
            return render(request, 'college/collegeinfo_create.html',context)
    else:
        raise Http404()
        
        

college/views/collegeinfo_delete.py
from college.models import CollegeInformation
from django.http import Http404
from django.contrib import messages
from django.shortcuts import redirect,render


def deleteCollegeInfo(request,id):
    collegeinfo = CollegeInformation.get_collegeinfo_by_id(id)
    if collegeinfo:
        if request.method == "POST":
            collegeinfo.delete()
            messages.success(request,"Information deleted successfully")
            return redirect('college_info:collegeinfo_list')
        return render(request,'college/collegeinfo_delete.html')
    else:
        raise Http404()

college/views/collegeinfo_detail.py
from multiprocessing import context
from django.shortcuts import render
from college.models import CollegeInformation
from django.http import Http404


def collegeInfoDetail(request,id):
    context = {}
    collegeinfo = CollegeInformation.get_collegeinfo_by_id(id)
    if collegeinfo:
        context = {'collegeinfo':collegeinfo}
        return render(request,'college/collegeinfo_detail.html',context)

college/views/collegeinfo_list.py
from college.models import CollegeInformation
from django.shortcuts import render

def listCollegeInfo(request):
    collegeinfo = CollegeInformation.get_all_collegeinfo()
    return render(request,'college/collegeinfo_list.html',{'college_info':collegeinfo})

college/views/collegeinfo_update.py
from http.client import HTTPResponse
from college.models import CollegeInformation
from django.http import Http404
from django.shortcuts import render
from college.forms import CollegeInfoForm

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse




def updateCollegeInfo(request,id):
    context = {}
    collegeinfo = CollegeInformation.get_collegeinfo_by_id(id)
    if collegeinfo:
        student = collegeinfo.student
        batch = collegeinfo.batch
        semester = collegeinfo.semester
        faculty = collegeinfo.faculty
        initial_dict = {
            'student':student.id,
            'batch':batch.id,
            'semester':semester.id,
            'faculty':faculty.id,
            'tu_registration_number':collegeinfo.tu_registration_number,
            'symbol_number':collegeinfo.symbol_number

        }
        if request.method == "POST":
            form = CollegeInfoForm(request.POST, instance = collegeinfo)
            if form.is_valid():
                form.save()
                messages.success(request,'Updated Successfully')
                return HttpResponseRedirect(reverse('college_info:collegeinfo_detail', args = [collegeinfo.id]))
                return HttpResponse("<h1>UPDATE SUCCESSFUL</h1>")
        else:
            form = CollegeInfoForm(initial = initial_dict)
            context = {'student':student,'batches':batch,'semesters':semester,'facultys':faculty} 
            return render(request,'college/collegeinfo_update.html',context)
    else:
        raise Http404()

college/templates/college/collegeinfo_create.html
{% extends 'student/base.html' %}

{% block title %}Family Information{% endblock %}


{% block content %}


<div>
    {% for message in messages %}
      {% if message %}
        <h4 style = "text-align:center;">{{message}}</h4>
      {% endif %}   
    {% endfor %}
  
  </div>

  
<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Family Information</h3>
                    </div>
                    <div class="card-body">
                        <form method = "POST" action = "">{% csrf_token %}  
                            {% comment %} {{form.as_p}} {% endcomment %}
                            <div class="form-group">
                                <select name = "student" class="form-control select2" style="width: 100%;">
                                  <option value = {{student.id}} selected="selected">{{student}}</option>
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "batch" class="form-control select2" style="width: 100%;">
                                    {% for batchs in batches %}
                                        <option value = {{batchs.id}}>{{batchs}}</option>
                                    {% endfor %} 
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "semester" class="form-control select2" style="width: 100%;">
                                    {% for sem in semesters %}
                                        <option value = {{sem.id}}>{{sem}}</option>
                                    {% endfor %}
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "faculty" class="form-control select2" style="width: 100%;">
                                    {% for facultys in faculties %}
                                        <option value = {{facultys.id}}>{{facultys}}</option>
                                    {% endfor %}
                                </select>
                            </div> 
                            <div class="form-group">
                                <label for="exampleInputTuregistration">Tu Registration Number</label>
                                <input type="text" class="form-control" id="exampleInputTuregistration" name = 'tu_registration_number'>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputSymbolNumber">Symbol Number</label>
                                <input type="text" class="form-control" id="exampleInputSymbolNumber" name = 'symbol_number'>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                        
          </div>
          <!-- /.card -->
            </div>
        </div>
    </div>
</section>


{% endblock content %}

college/templates/college/collegeinfo_delete.html
{% extends 'student/base.html' %}

{% block title %}Delete CollegeInfo{% endblock %}


{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
            <!-- general form elements -->
                <div class="card card-primary">
                    <form method = "POST">
                        {% csrf_token %}
                        Are you sure to delete this student's college information?
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

college/templates/college/collegeinfo_detail.html
{% extends 'student/base.html' %}

{% block title %}CollegeInfo Detail{% endblock %}


{% block content %}

<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class = "wrapper">

    <h4 class="mb-2 mt-4">{{collegeinfo.student.name}}||College Information</h4>
        <div class="row">
          <div class="col-md-3">
            <div class="card card-primary collapsed-card">
              <div class="card-header">
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <span>Student:<p>{{collegeinfo.student.name}}<p></span><br>
                <span>Board:<p>{{collegeinfo.board}}<p></span><br>
                <span>Semester:<p>{{collegeinfo.semester}}<p></span><br>

                <span>Faculty:<p>{{collegeinfo.faculty}}<p></span><br>
                <span>Registration Number:<p>{{collegeinfo.tu_registration_number}}<p></span><br>
                <span>Symbol:<p>{{collegeinfo.symbol_number}}<p></span><br>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
</div>

{% endblock content %}

college/templates/college/collegeinfo_list.html
{% extends 'student/base.html' %}

{% block title %}List CollegeInfo{% endblock %}


{% block content %}

<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">College Information List</h3>
        </div>
      </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>SN</th>
                <th>Student</th>
                <th>Batch</th>
                <th>Semester</th>
                <th>Faculty</th>
                <th>Action</th>
              </tr>
            </thead>
            {% for collegeinfo in college_info %}
            <tbody>
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{collegeinfo.student}}</td>
                <td>{{collegeinfo.batch.batch_name}}</td>
                <td>{{collegeinfo.semester.semester_name}}</td>
                <td>{{collegeinfo.faculty.faculty_name}}</td>
                <td>
                    <a href = "{% url 'college_info:collegeinfo_detail' collegeinfo.id %}" class = "btn btn-info btn-sm"><span class = "fa fa-eye"></span></a>
                    <a href = "{% url 'college_info:collegeinfo_update' collegeinfo.id %}" class = "btn btn-warning btn-sm"><span class = "fa fa-edit"></span></a>
                    <a href = "{% url 'college_info:collegeinfo_delete' collegeinfo.id %}" class = "btn btn-danger btn-sm"><span class = "fa fa-trash"></span></a>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


{% endblock content %}

college/templates/college/collegeinfo_update.html
{% extends 'student/base.html' %}

{% block title %}College Information{% endblock %}


{% block content %}


<div>
    {% for message in messages %}
      {% if message %}
        <h4 style = "text-align:center;">{{message}}</h4>
      {% endif %}   
    {% endfor %}
  
  </div>

  
<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Colleg Information</h3>
                    </div>
                    <div class="card-body">
                        <form method = "POST" action = "">{% csrf_token %}  
                            {% comment %} {{form.as_p}} {% endcomment %}
                            <div class="form-group">
                                <select name = "student" class="form-control select2" style="width: 100%;">
                                  <option value = {{student.id}} selected="selected">{{student}}</option>
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "batch" class="form-control select2" style="width: 100%;">
                                    <option value = {{batches.id}}>{{batches}}</option>
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "semester" class="form-control select2" style="width: 100%;">
                                    <option value = {{semesters.id}}>{{semesters}}</option>
                                </select>
                            </div> 
                            <div class="form-group">
                                <select name = "faculty" class="form-control select2" style="width: 100%;">
                                    <option value = {{facultys.id}}>{{facultys}}</option>
                                </select>
                            </div> 
                            <div class="form-group">
                                <label for="exampleInputTuregistration">Tu Registration Number</label>
                                <input type="text" class="form-control" id="exampleInputTuregistration" name = 'tu_registration_number'>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputSymbolNumber">Symbol Number</label>
                                <input type="text" class="form-control" id="exampleInputSymbolNumber" name = 'symbol_number'>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                        
          </div>
          <!-- /.card -->
            </div>
        </div>
    </div>
</section>


{% endblock content %}