batch/urls.py
from django.urls import path
from batch.views import create_batch, update_batch, detail_batch, list_batch, delete_batch

app_name = 'batch'

urlpatterns = [
    path('create_batch',create_batch.createBatch, name = 'create_batch'),
    path('update_batch/<str:id>',update_batch.updateBatch, name = 'update_batch'),
    path('detail_batch/<str:id>',detail_batch.detailBatch, name = 'detail_batch'),
    path('list_batch',list_batch.listBatch, name = 'list_batch'),
    path('delete_batch/<str:id>',delete_batch.deleteBatch,name = 'delete_batch')



    
]

education/urls.py
from django.urls import path
from .views import educationinfo_create,eudcationinfo_list,educationinfo_detail,educationinfo_update,educationinfo_delete

app_name = 'education'

urlpatterns = [
    
   # requires student id
    path('educationinfo_create/<str:id>',educationinfo_create.createEducationInfo,name = 'educationinfo_create'),
    path('educationinfo_list',eudcationinfo_list.listEducationInfo,name = 'educationinfo_list'),
    # requires educationinformation id
    path('educationinfo_detail/<str:id>',educationinfo_detail.educationinfoDetail,name = 'educationinfo_detail'),
    # requires educationinformation id
    path('educationinfo_update/<str:id>',educationinfo_update.updateEducationInfo,name = 'educationinfo_update'),
   # requires educationinformation id
    path('educationinfo_delete/<str:id>',educationinfo_delete.deleteEducationInfo,name = 'educationinfo_delete'),

]

registration_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    path('batch/',include('batch.urls')),
    path('',include('education.urls')),
    path('',include('family.urls')),
    path('',include('college.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education/models.py
from django.db import models
from student.models import Student
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404



# Create your models here.
class EducationInformation(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    symbol_number = models.CharField(max_length=50)
    board = models.CharField(max_length=50)
    institution_name  = models.CharField(max_length=50)
    cgpa = models.CharField(max_length=50)
    passed_year = models.CharField(max_length=50)

    class Meta:
        ordering = ('symbol_number',)
        verbose_name = "EducationInformation"
        verbose_name_plural = "EducationInformations"

    @staticmethod
    def get_all_educationinfo():
        return EducationInformation.objects.all()

    @staticmethod
    def get_educationinfo_by_id(id):
        try:
            return EducationInformation.objects.get(id = id)
        except ObjectDoesNotExist:
            return None

education/forms.py
from education.models import EducationInformation
from django import forms


class EducationInfoForm(forms.ModelForm):

    class Meta:
        model = EducationInformation
        fields = "__all__"

education/views/educationinfo_create.py
from django.http import HttpResponse,HttpResponseRedirect,Http404
from education.forms import EducationInfoForm
from django.contrib import messages
from django.shortcuts import render,HttpResponse,redirect

from student.models import Student


def createEducationInfo(request,id):
    student = Student.get_student_by_id(id)
    if student:
        if request.method == "GET":
            form = EducationInfoForm(instance=student)
            return render(request,'education/educationinfo_create.html',{'form':form,'student':student})

        elif request.method == "POST":
            form = EducationInfoForm(request.POST)
            if form.is_valid():
                form.save(commit=True)
                messages.success(request,'Successfully created')
                return redirect('education:educationinfo_list')

            else:
                return HttpResponse("<h1>Form not valid</h1>")
        return render(request,'education/educationinfo_create.html',{'form':form,'student':student})
    else:
        raise Http404()

education/views/educationinfo_delete.py
from django.http import HttpResponse
from django.shortcuts import redirect
from education.models import EducationInformation

from django.shortcuts import redirect, render
from django.http import Http404
from django.contrib import messages

def deleteEducationInfo(request,id):
    educationinfo = EducationInformation.get_educationinfo_by_id(id)
    if educationinfo:
        if request.method == "POST":
            educationinfo.delete()
            messages.success(request,"Information deleted successfully")
            return redirect('education:educationinfo_list')
        return render(request,'education/educationinfo_delete.html')
    else:
        raise Http404()

education/views/educationinfo_detail.py
from django.shortcuts import render
from education.models import EducationInformation
from django.http import Http404

def educationinfoDetail(request,id):
    context = {}
    educationinfo = EducationInformation.get_educationinfo_by_id(id)
    if educationinfo:
        context['educationinfo'] = educationinfo
        return render(request,'education/educationinfo_detail.html',context)
    else:
        raise Http404()

education/views/educationinfo_update.py
from django.http import HttpResponseRedirect, Http404
from student.models import Student
from education.models import EducationInformation

from education.forms import EducationInfoForm
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse

def updateEducationInfo(request,id):
    context = {}
    educationinfo = EducationInformation.get_educationinfo_by_id(id)
    student = educationinfo.student
    if educationinfo:
        initial_dict = {
            'student':student.id,
            'symbol_number':educationinfo.symbol_number,
            'board':educationinfo.board,
            'institution_name':educationinfo.institution_name,
            'cgpa':educationinfo.cgpa,
            'passed_year':educationinfo.passed_year
        }
        if request.method == "POST":
            form = EducationInfoForm(request.POST,instance=educationinfo)
            if form.is_valid():
                form.save()
                messages.success(request,'Updated Successfully')
                return HttpResponseRedirect(reverse('education:educationinfo_detail', args = [educationinfo.id]))

        else:
            form = EducationInfoForm(initial = initial_dict)
        context = {'form':form, 'student':student}

        return render(request,'education/educationinfo_update.html',context)
        

    else:
        raise Http404()

education/views/eudcationinfo_list.py
from student.models import Student
from education.models import EducationInformation

from django.shortcuts import render

def listEducationInfo(request):
    students = Student.get_all_student()
    educationinfo = EducationInformation.get_all_educationinfo()
    return render(request,'education/educationinfo_list.html',{'students':students,'education_info':educationinfo})

education/templates/education/educationinfo_create.html
{% extends 'student/base.html' %}

{% block title %}Education Information{% endblock %}


{% block content %}


<div>
    {% for message in messages %}
      {% if message %}
        <h4 style = "text-align:center;">{{message}}</h4>
      {% endif %}   
    {% endfor %}
  
  </div>

  
<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Education Information</h3>
                    </div>
                    <div class="card-body">
                        <form method = "POST" action = "{% url 'education:educationinfo_create' student.id %}">{% csrf_token %}  
                            {% comment %} {{form.as_p}} {% endcomment %}
                            <div class="form-group">
                                <select hidden name = "student" class="form-control select2" style="width: 100%;">
                                  <option selected="selected">{{student.id}}</option>
                                </select>
                              </div> 
                            <div class="form-group">
                                <label for="exampleInputSymbol">Symbol_number</label>
                                <input type="text" class="form-control" id="exampleInputSymbol" name = 'symbol_number' placeholder="Enter symbol">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputBoard">Board</label>
                                <input type="text" class="form-control" id="exampleInputBoard" name = 'board' placeholder="Enter Board">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputInstitution">Institution Name</label>
                                <input type="text" class="form-control" id="exampleInputInstitution" name = 'institution_name' placeholder="Enter Institution Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputCgpa">Cgpa</label>
                                <input type="text" class="form-control" id="exampleInputCgpa" name = 'cgpa' placeholder="Enter Cgpa" >
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassedYear">Passed Year</label>
                                <input type="text" class="form-control" id="exampleInputPassedYear" name = 'passed_year' placeholder="Enter Passed Year">
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                        
          </div>
          <!-- /.card -->
            </div>
        </div>
    </div>
</section>


{% endblock content %}

education/templates/education/educationinfo_delete.html
{% extends 'student/base.html' %}

{% block title %}Delete EduInfo{% endblock %}


{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
            <!-- general form elements -->
                <div class="card card-primary">
                    <form method = "POST">
                        {% csrf_token %}
                        Are you sure to delete this student?
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

education/templates/education/educationinfo_detail.html
{% extends 'student/base.html' %}

{% block title %}EduInfo Detail{% endblock %}


{% block content %}

<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class = "wrapper">

    <h4 class="mb-2 mt-4">{{educationinfo.student.name}}||Education Information</h4>
        <div class="row">
          <div class="col-md-3">
            <div class="card card-primary collapsed-card">
              <div class="card-header">
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <span>Student Name:<p>{{educationinfo.student.name}}<p></span><br>
                <span>Board:<p>{{educationinfo.board}}<p></span><br>
                <span>Symbol Number:<p>{{educationinfo.symbol_number}}<p></span><br>
                <span>Institution:<p>{{educationinfo.institution_name}}<p></span><br>
                <span>CGPA:<p>{{educationinfo.cgpa}}<p></span><br>
                <span>Passed Year:<p>{{educationinfo.passed_year}}<p></span><br>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
</div>

{% endblock content %}

education/templates/education/educationinfo_list.html
{% extends 'student/base.html' %}

{% block title %}List EduInfo{% endblock %}


{% block content %}

<div>
  {% for message in messages %}
    {% if message %}
      <h4 style = "text-align:center;">{{message}}</h4>
    {% endif %}   
  {% endfor %}

</div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Education Information List</h3>
        </div>
      </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>SN</th>
                <th>Student</th>
                <th>Symbol</th>
                <th>Board</th>
                <th>Institution</th>
                <th>CGPA</th>
                <th>Passed Year</th>
                <th>Action</th>
              </tr>
            </thead>
            {% for education in education_info %}
            <tbody>
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{education.student.name}}</td>
                <td>{{education.symbol_number}}</td>
                <td>{{education.board}}</td>
                <td>{{education.institution_name}}</td>
                <td>{{education.cgpa}}</td>
                <td>{{education.passed_year}}</td>
                <td>
                    <a href = "{% url 'education:educationinfo_detail' education.id %}" class = "btn btn-info btn-sm"><span class = "fa fa-eye"></span></a>
                    <a href = "{% url 'education:educationinfo_update' education.id %}" class = "btn btn-warning btn-sm"><span class = "fa fa-edit"></span></a>
                    <a href = "{% url 'education:educationinfo_delete' education.id %}" class = "btn btn-danger btn-sm"><span class = "fa fa-trash"></span></a>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


{% endblock content %}

education/templates/education/educationinfo_update.html
{% extends 'student/base.html' %}

{% block title %}Update EduInfo{% endblock %}


{% block content %}


<div>
    {% for message in messages %}
      {% if message %}
        <h4 style = "text-align:center;">{{message}}</h4>
      {% endif %}   
    {% endfor %}
  
  </div>

  
<section class="content">
    <div class="container-fluid">
        <div class="row">
        <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Education Information</h3>
                    </div>
                    <div class="card-body">
                        <form method = "POST">{% csrf_token %}  
                            {% comment %} {{form.as_p}} {% endcomment %}
                            <div class="form-group">
                                <select hidden name = "student" class="form-control select2" style="width: 100%;">
                                  <option selected="selected">{{student.id}}</option>
                                </select>
                              </div> 
                            <div class="form-group">
                                <label for="exampleInputSymbol">Symbol_number</label>
                                <input type="text" class="form-control" id="exampleInputSymbol" name = 'symbol_number' placeholder="Enter symbol">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputBoard">Board</label>
                                <input type="text" class="form-control" id="exampleInputBoard" name = 'board' placeholder="Enter Board">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputInstitution">Institution Name</label>
                                <input type="text" class="form-control" id="exampleInputInstitution" name = 'institution_name' placeholder="Enter Institution Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputCgpa">Cgpa</label>
                                <input type="text" class="form-control" id="exampleInputCgpa" name = 'cgpa' placeholder="Enter Cgpa" >
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassedYear">Passed Year</label>
                                <input type="text" class="form-control" id="exampleInputPassedYear" name = 'passed_year' placeholder="Enter Passed Year">
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                        
          </div>
          <!-- /.card -->
            </div>
        </div>
    </div>
</section>


{% endblock content %}